name: location_pro_example
description: A Flutter example app to test the Location Pro package locally.
version: 1.0.0
homepage: https://github.com/mdabdullahalsiddik/location_pro
publish_to: "none" # Example apps are not published to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local dependency to test your package
  location_pro:
    path: ../   # Points to your local 'location_pro' package folder

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
