name: location_pro
description: A Flutter package to fetch current location, track live position, and get addresses in multiple languages using OpenStreetMap Nominatim.
version: 1.0.0
homepage: https://github.com/mdabdullahalsiddik/location_pro
publish_to: "none" # Remove this if you want to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.2.0
  http: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

